### ISSUE TITLE
Election title - unable to save ("continue" button is deactivated)

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/bettervoting#926]
Election title - unable to save ("continue" button is deactivated) - see video: https://youtu.be/uK7vgQKJRc4

**Comment by ArendPeter** [comment]
We need to double check our validation rules, and make it more clear to the user

**Comment by masiarek** [comment]
Please resolve - it is hard to test the Editable Ballots.

**Comment by ArendPeter** [comment]
This has now been fixed! My bad for the delay, I thought I fixed this a long time ago 😪

**Comment by masiarek** [comment]
I still see the limitation of 50 characters - if this is "by design" - pls close.

Try entering this long string: 0123456789a123456789b123456789c123456789d123456789

**Comment by masiarek** [comment]
retested OK - https://bettervoting.com/q78tf9/admin

closing issue.
